### ISSUE TITLE
`compileOnly` dependencies for `api`

### ISSUE THREAD

**Issue by nomisRev** [kotest/kotest-extensions-arrow#130]
https://github.com/kotest/kotest-extensions-arrow/blob/adaad79045b91882a84b19fa2bdf6a9573e4f962/kotest-assertions-arrow/build.gradle.kts#L154

When a library uses a dependency in its API it must be declared as an `api` dependency.
Otherwise, consumers of the library need to explicitly declare dependencies on all transitive dependencies.

Slack discussion: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1640730079383100

**Comment by i-walker** [comment]
As discussed in the Thread,
In most applications, where the dependency is already in the compile classpath this would lead to dependency conflicts between instances or/and versions. People would then have to exclude those dependencies in their classpath.

I'll add docs for adding the respective arrow library, both to the Kotest Docs and here in the README :D 
https://github.com/kotest/kotest/pull/2753
