### ISSUE TITLE
shouldBeLeft() messes up typing

### ISSUE THREAD

**Issue by shalbert94** [kotest/kotest-extensions-arrow#99]
`shouldBeLeft()`'s `contract` appears to mess up typing. In the example below, `it` in ` actual.mapLeft { it }` should be a `Throwable`, but because `actual.shouldBeLeft()` is called first, `it` is of type `Any?`. This appears to be caused by `shouldBeLeft()`'s contract 

```
contract {
        returns() implies (this@shouldBeLeft is Either.Left<*>)
    }
```

Example:
```
import arrow.core.Either
import arrow.core.left
import io.kotest.assertions.arrow.either.shouldBeLeft
import io.kotest.core.spec.style.StringSpec
import java.lang.IllegalArgumentException

class Right

class Sample: StringSpec({
    "Example"{
            val actual: Either<Throwable, Right> = IllegalArgumentException().left()

            actual.shouldBeLeft()
            actual.mapLeft { it } //Why is [it] of type Any?
        }
})
```

**Comment by i-walker** [comment]
This is an issue in your example. 
```kotlin
val actual: Either<Throwable, Int> = IllegalArgumentException().left()

    actual.shouldBeLeft()
    actual.mapLeft { it } // it is properly resolved
```
Do you have another example or repo I can check out

**Comment by shalbert94** [comment]
Closed because I was referencing 1.0.1 instead of 1.1.1, which has a different implementation of `shouldBeLeft()`.

Reopening because the upgrade doesn't resolve the issue. Preparing a sample repo now.

**Comment by shalbert94** [comment]
Apologies, this was caused by me referencing 1.0.1 instead of 1.1.1, which has a different contract.

**Comment by i-walker** [comment]
No apologies needed 😄 @shalbert94
